#March Machine Learning Mania 2016 -Kaggle

###Goal: Predict the 2016 NCAA Basketball Tournament

#### Step 1:Import libraries

In [858]:
import pandas as pd
import numpy as np
import csv
from sklearn import ensemble
from sklearn.metrics import log_loss
from sklearn.preprocessing import StandardScaler
from sklearn.ensemble import RandomForestClassifier

#### Step 2: Writing function that aggregates data

In [859]:
#This function aggregates data in a right order
def Aggregate(teamcompactresults1,
              teamcompactresults2,
              merged_results,
              regularseasoncompactresults):
    winningteam1compactresults = pd.merge(how='left',
                                          left=teamcompactresults1,
                                          right=regularseasoncompactresults,
                                          left_on=['year', 'team1'],
                                          right_on=['Season', 'Wteam'])
    winningteam1compactresults.drop(['Season',
                                     'Daynum',
                                     'Wteam',
                                     'Lteam',
                                     'Lscore',
                                     'Wloc',
                                     'Numot'],
                                    inplace=True,
                                    axis=1)
    grpwinningteam1resultsaverage =  \
        winningteam1compactresults.groupby(['year', 'team1']).mean()
    winningteam1resultsaverage = grpwinningteam1resultsaverage.reset_index()
    winningteam1resultsaverage.rename(columns={'Wscore': 'team1WAverage'},
                                      inplace=True)
    grpwinningteam1resultsmin =  \
        winningteam1compactresults.groupby(['year', 'team1']).min()
    winningteam1resultsmin = grpwinningteam1resultsmin.reset_index()
    winningteam1resultsmin.rename(columns={'Wscore': 'team1Wmin'},
                                  inplace=True)
    grpwinningteam1resultsmax =  \
        winningteam1compactresults.groupby(['year', 'team1']).max()
    winningteam1resultsmax = grpwinningteam1resultsmax.reset_index()
    winningteam1resultsmax.rename(columns={'Wscore': 'team1Wmax'},
                                  inplace=True)
    grpwinningteam1resultsmedian =  \
        winningteam1compactresults.groupby(['year', 'team1']).median()
    winningteam1resultsmedian = grpwinningteam1resultsmedian.reset_index()
    winningteam1resultsmedian.rename(columns={'Wscore': 'team1Wmedian'},
                                     inplace=True)
    grpwinningteam1resultsstd =  \
        winningteam1compactresults.groupby(['year', 'team1']).std()
    winningteam1resultsstd = grpwinningteam1resultsstd.reset_index()
    winningteam1resultsstd.rename(columns={'Wscore': 'team1Wstd'},
                                  inplace=True)
    losingteam1compactresults = pd.merge(how='left',
                                         left=teamcompactresults1,
                                         right=regularseasoncompactresults,
                                         left_on=['year', 'team1'],
                                         right_on=['Season', 'Lteam'])
    losingteam1compactresults.drop(['Season',
                                    'Daynum',
                                    'Wteam',
                                    'Lteam',
                                    'Wscore',
                                    'Wloc',
                                    'Numot'],
                                   inplace=True,
                                   axis=1)
    grplosingteam1resultsaverage = \
        losingteam1compactresults.groupby(['year', 'team1']).mean()
    losingteam1resultsaverage = grplosingteam1resultsaverage.reset_index()
    losingteam1resultsaverage.rename(columns={'Lscore': 'team1LAverage'},
                                     inplace=True)
    grplosingteam1resultsmin = \
        losingteam1compactresults.groupby(['year', 'team1']).min()
    losingteam1resultsmin = grplosingteam1resultsmin.reset_index()
    losingteam1resultsmin.rename(columns={'Lscore': 'team1Lmin'},
                                 inplace=True)
    grplosingteam1resultsmax = \
        losingteam1compactresults.groupby(['year', 'team1']).max()
    losingteam1resultsmax = grplosingteam1resultsmax.reset_index()
    losingteam1resultsmax.rename(columns={'Lscore': 'team1Lmax'},
                                 inplace=True)
    grplosingteam1resultsmedian = \
        losingteam1compactresults.groupby(['year', 'team1']).median()
    losingteam1resultsmedian = grplosingteam1resultsmedian.reset_index()
    losingteam1resultsmedian.rename(columns={'Lscore': 'team1Lmedian'},
                                    inplace=True)
    grplosingteam1resultsstd = \
        losingteam1compactresults.groupby(['year', 'team1']).std()
    losingteam1resultsstd = grplosingteam1resultsstd.reset_index()
    losingteam1resultsstd.rename(columns={'Lscore': 'team1Lstd'},
                                 inplace=True)
    winningteam2compactresults = pd.merge(how='left',
                                          left=teamcompactresults2,
                                          right=regularseasoncompactresults,
                                          left_on=['year', 'team2'],
                                          right_on=['Season', 'Wteam'])
    winningteam2compactresults.drop(['Season',
                                     'Daynum',
                                     'Wteam',
                                     'Lteam',
                                     'Lscore',
                                     'Wloc',
                                     'Numot'],
                                    inplace=True,
                                    axis=1)
    grpwinningteam2resultsaverage = \
        winningteam2compactresults.groupby(['year', 'team2']).mean()
    winningteam2resultsaverage = grpwinningteam2resultsaverage.reset_index()
    winningteam2resultsaverage.rename(columns={'Wscore': 'team2WAverage'},
                                      inplace=True)
    grpwinningteam2resultsmin = \
        winningteam2compactresults.groupby(['year', 'team2']).min()
    winningteam2resultsmin = grpwinningteam2resultsmin.reset_index()
    winningteam2resultsmin.rename(columns={'Wscore': 'team2Wmin'},
                                  inplace=True)
    grpwinningteam2resultsmax = \
        winningteam2compactresults.groupby(['year', 'team2']).max()
    winningteam2resultsmax = grpwinningteam2resultsmax.reset_index()
    winningteam2resultsmax.rename(columns={'Wscore': 'team2Wmax'},
                                  inplace=True)
    grpwinningteam2resultsmedian = \
        winningteam2compactresults.groupby(['year', 'team2']).median()
    winningteam2resultsmedian = grpwinningteam2resultsmedian.reset_index()
    winningteam2resultsmedian.rename(columns={'Wscore': 'team2Wmedian'},
                                     inplace=True)
    grpwinningteam2resultsstd = \
        winningteam2compactresults.groupby(['year', 'team2']).std()
    winningteam2resultsstd = grpwinningteam2resultsstd.reset_index()
    winningteam2resultsstd.rename(columns={'Wscore': 'team2Wstd'},
                                  inplace=True)
    losingteam2compactresults = pd.merge(how='left',
                                         left=teamcompactresults2,
                                         right=regularseasoncompactresults,
                                         left_on=['year', 'team2'],
                                         right_on=['Season', 'Lteam'])
    losingteam2compactresults.drop(['Season',
                                    'Daynum',
                                    'Wteam',
                                    'Lteam',
                                    'Wscore',
                                    'Wloc',
                                    'Numot'],
                                   inplace=True,
                                   axis=1)
    grplosingteam2resultsaverage = \
        losingteam2compactresults.groupby(['year', 'team2']).mean()
    losingteam2resultsaverage = grplosingteam2resultsaverage.reset_index()
    losingteam2resultsaverage.rename(columns={'Lscore': 'team2LAverage'},
                                     inplace=True)
    grplosingteam2resultsmin = \
        losingteam2compactresults.groupby(['year', 'team2']).min()
    losingteam2resultsmin = grplosingteam2resultsmin.reset_index()
    losingteam2resultsmin.rename(columns={'Lscore': 'team2Lmin'},
                                 inplace=True)
    grplosingteam2resultsmax = \
        losingteam2compactresults.groupby(['year', 'team2']).max()
    losingteam2resultsmax = grplosingteam2resultsmax.reset_index()
    losingteam2resultsmax.rename(columns={'Lscore': 'team2Lmax'},
                                 inplace=True)
    grplosingteam2resultsmedian = \
        losingteam2compactresults.groupby(['year', 'team2']).median()
    losingteam2resultsmedian = grplosingteam2resultsmedian.reset_index()
    losingteam2resultsmedian.rename(columns={'Lscore': 'team2Lmedian'},
                                    inplace=True)
    grplosingteam2resultsstd = \
        losingteam2compactresults.groupby(['year', 'team2']).std()
    losingteam2resultsstd = grplosingteam2resultsstd.reset_index()
    losingteam2resultsstd.rename(columns={'Lscore': 'team2Lstd'},
                                 inplace=True)
    agg_results = pd.merge(how='left',
                           left=merged_results,
                           right=winningteam1resultsaverage,
                           left_on=['year', 'team1'],
                           right_on=['year', 'team1'])
    agg_results = pd.merge(how='left',
                           left=agg_results,
                           right=losingteam1resultsaverage,
                           left_on=['year', 'team1'],
                           right_on=['year', 'team1'])
    agg_results = pd.merge(how='left',
                           left=agg_results,
                           right=winningteam1resultsmin,
                           left_on=['year', 'team1'],
                           right_on=['year', 'team1'])
    agg_results = pd.merge(how='left',
                           left=agg_results,
                           right=losingteam1resultsmin,
                           left_on=['year', 'team1'],
                           right_on=['year', 'team1'])
    agg_results = pd.merge(how='left',
                           left=agg_results,
                           right=winningteam1resultsmax,
                           left_on=['year', 'team1'],
                           right_on=['year', 'team1'])
    agg_results = pd.merge(how='left',
                           left=agg_results,
                           right=losingteam1resultsmax,
                           left_on=['year', 'team1'],
                           right_on=['year', 'team1'])
    agg_results = pd.merge(how='left',
                           left=agg_results,
                           right=winningteam1resultsmedian,
                           left_on=['year', 'team1'],
                           right_on=['year', 'team1'])
    agg_results = pd.merge(how='left',
                           left=agg_results,
                           right=losingteam1resultsmedian,
                           left_on=['year', 'team1'],
                           right_on=['year', 'team1'])
    agg_results = pd.merge(how='left',
                           left=agg_results,
                           right=winningteam1resultsstd,
                           left_on=['year', 'team1'],
                           right_on=['year', 'team1'])
    agg_results = pd.merge(how='left',
                           left=agg_results,
                           right=losingteam1resultsstd,
                           left_on=['year', 'team1'],
                           right_on=['year', 'team1'])
    agg_results = pd.merge(how='left',
                           left=agg_results,
                           right=winningteam2resultsaverage,
                           left_on=['year', 'team2'],
                           right_on=['year', 'team2'])
    agg_results = pd.merge(how='left',
                           left=agg_results,
                           right=losingteam2resultsaverage,
                           left_on=['year', 'team2'],
                           right_on=['year', 'team2'])
    agg_results = pd.merge(how='left',
                           left=agg_results,
                           right=winningteam2resultsmin,
                           left_on=['year', 'team2'],
                           right_on=['year', 'team2'])
    agg_results = pd.merge(how='left',
                           left=agg_results,
                           right=losingteam2resultsmin,
                           left_on=['year', 'team2'],
                           right_on=['year', 'team2'])
    agg_results = pd.merge(how='left',
                           left=agg_results,
                           right=winningteam2resultsmax,
                           left_on=['year', 'team2'],
                           right_on=['year', 'team2'])
    agg_results = pd.merge(how='left',
                           left=agg_results,
                           right=losingteam2resultsmax,
                           left_on=['year', 'team2'],
                           right_on=['year', 'team2'])
    agg_results = pd.merge(how='left',
                           left=agg_results,
                           right=winningteam2resultsmedian,
                           left_on=['year', 'team2'],
                           right_on=['year', 'team2'])
    agg_results = pd.merge(how='left',
                           left=agg_results,
                           right=losingteam2resultsmedian,
                           left_on=['year', 'team2'],
                           right_on=['year', 'team2'])
    agg_results = pd.merge(how='left',
                           left=agg_results,
                           right=winningteam2resultsstd,
                           left_on=['year', 'team2'],
                           right_on=['year', 'team2'])
    agg_results = pd.merge(how='left',
                           left=agg_results,
                           right=losingteam2resultsstd,
                           left_on=['year', 'team2'],
                           right_on=['year', 'team2'])
    return agg_results

In [860]:
def GrabData():
    tourneyresults = pd.read_csv('TourneyCompactResults.csv')
    tourneyseeds = pd.read_csv('TourneySeeds.csv')
    regularseasoncompactresults = \
        pd.read_csv('RegularSeasonCompactResults.csv')
    sample = pd.read_csv('SampleSubmission.csv')
    results = pd.DataFrame()
    results['year'] = tourneyresults.Season
    results['team1'] = np.minimum(tourneyresults.Wteam, tourneyresults.Lteam)
    results['team2'] = np.maximum(tourneyresults.Wteam, tourneyresults.Lteam)
    results['result'] = (tourneyresults.Wteam <
                         tourneyresults.Lteam).astype(int)
    merged_results = pd.merge(left=results,
                              right=tourneyseeds,
                              left_on=['year', 'team1'],
                              right_on=['Season', 'Team'])
    merged_results.drop(['Season', 'Team'], inplace=True, axis=1)
    merged_results.rename(columns={'Seed': 'team1Seed'}, inplace=True)
    merged_results = pd.merge(left=merged_results,
                              right=tourneyseeds,
                              left_on=['year', 'team2'],
                              right_on=['Season', 'Team'])
    merged_results.drop(['Season', 'Team'], inplace=True, axis=1)
    merged_results.rename(columns={'Seed': 'team2Seed'}, inplace=True)
    merged_results['team1Seed'] = \
        merged_results['team1Seed'].apply(lambda x: str(x)[1:3])
    merged_results['team2Seed'] = \
        merged_results['team2Seed'].apply(lambda x: str(x)[1:3])
    merged_results = merged_results.astype(int)
    winsbyyear = regularseasoncompactresults[['Season', 'Wteam']].copy()
    winsbyyear['wins'] = 1
    wins = winsbyyear.groupby(['Season', 'Wteam']).sum()
    wins = wins.reset_index()
    lossesbyyear = regularseasoncompactresults[['Season', 'Lteam']].copy()
    lossesbyyear['losses'] = 1
    losses = lossesbyyear.groupby(['Season', 'Lteam']).sum()
    losses = losses.reset_index()
    winsteam1 = wins.copy()
    winsteam1.rename(columns={'Season': 'year',
                              'Wteam': 'team1',
                              'wins': 'team1wins'}, inplace=True)
    winsteam2 = wins.copy()
    winsteam2.rename(columns={'Season': 'year',
                              'Wteam': 'team2',
                              'wins': 'team2wins'}, inplace=True)
    lossesteam1 = losses.copy()
    lossesteam1.rename(columns={'Season': 'year',
                                'Lteam': 'team1',
                                'losses': 'team1losses'}, inplace=True)
    lossesteam2 = losses.copy()
    lossesteam2.rename(columns={'Season': 'year',
                                'Lteam': 'team2',
                                'losses': 'team2losses'}, inplace=True)
    merged_results = pd.merge(how='left',
                              left=merged_results,
                              right=winsteam1,
                              left_on=['year', 'team1'],
                              right_on=['year', 'team1'])
    merged_results = pd.merge(how='left',
                              left=merged_results,
                              right=lossesteam1,
                              left_on=['year', 'team1'],
                              right_on=['year', 'team1'])
    merged_results = pd.merge(how='left',
                              left=merged_results,
                              right=winsteam2,
                              left_on=['year', 'team2'],
                              right_on=['year', 'team2'])
    merged_results = pd.merge(how='left',
                              left=merged_results,
                              right=lossesteam2,
                              left_on=['year', 'team2'],
                              right_on=['year', 'team2'])
    teamcompactresults1 = merged_results[['year', 'team1']].copy()
    teamcompactresults2 = merged_results[['year', 'team2']].copy()

    train = Aggregate(teamcompactresults1,
                      teamcompactresults2,
                      merged_results,
                      regularseasoncompactresults)

    sample['year'] = sample.Id.apply(lambda x: str(x)[:4]).astype(int)
    sample['team1'] = sample.Id.apply(lambda x: str(x)[5:9]).astype(int)
    sample['team2'] = sample.Id.apply(lambda x: str(x)[10:14]).astype(int)

    merged_results = pd.merge(how='left',
                              left=sample,
                              right=tourneyseeds,
                              left_on=['year', 'team1'],
                              right_on=['Season', 'Team'])
    merged_results.drop(['Season', 'Team'], inplace=True, axis=1)
    merged_results.rename(columns={'Seed': 'team1Seed'}, inplace=True)
    merged_results = pd.merge(how='left',
                              left=merged_results,
                              right=tourneyseeds,
                              left_on=['year', 'team2'],
                              right_on=['Season', 'Team'])
    merged_results.drop(['Season', 'Team'], inplace=True, axis=1)
    merged_results.rename(columns={'Seed': 'team2Seed'}, inplace=True)
    merged_results['team1Seed'] = \
        merged_results['team1Seed'].apply(lambda x: str(x)[1:3]).astype(int)
    merged_results['team2Seed'] = \
        merged_results['team2Seed'].apply(lambda x: str(x)[1:3]).astype(int)
    merged_results = pd.merge(how='left',
                              left=merged_results,
                              right=winsteam1,
                              left_on=['year', 'team1'],
                              right_on=['year', 'team1'])
    merged_results = pd.merge(how='left',
                              left=merged_results,
                              right=lossesteam1,
                              left_on=['year', 'team1'],
                              right_on=['year', 'team1'])
    merged_results = pd.merge(how='left',
                              left=merged_results,
                              right=winsteam2,
                              left_on=['year', 'team2'],
                              right_on=['year', 'team2'])
    merged_results = pd.merge(how='left',
                              left=merged_results,
                              right=lossesteam2,
                              left_on=['year', 'team2'],
                              right_on=['year', 'team2'])

    teamcompactresults1 = merged_results[['year', 'team1']].copy()
    teamcompactresults2 = merged_results[['year', 'team2']].copy()

    test = Aggregate(teamcompactresults1,
                     teamcompactresults2,
                     merged_results,
                     regularseasoncompactresults)

    return train, test

In [861]:
train, test = GrabData()

In [862]:
list(train.columns.values)

['year',
 'team1',
 'team2',
 'result',
 'team1Seed',
 'team2Seed',
 'team1wins',
 'team1losses',
 'team2wins',
 'team2losses',
 'team1WAverage',
 'team1LAverage',
 'team1Wmin',
 'team1Lmin',
 'team1Wmax',
 'team1Lmax',
 'team1Wmedian',
 'team1Lmedian',
 'team1Wstd',
 'team1Lstd',
 'team2WAverage',
 'team2LAverage',
 'team2Wmin',
 'team2Lmin',
 'team2Wmax',
 'team2Lmax',
 'team2Wmedian',
 'team2Lmedian',
 'team2Wstd',
 'team2Lstd']

In [863]:
train.head(10)

,year,team1,team2,result,team1Seed,team2Seed,team1wins,team1losses,team2wins,team2losses,...,team2WAverage,team2LAverage,team2Wmin,team2Lmin,team2Wmax,team2Lmax,team2Wmedian,team2Lmedian,team2Wstd,team2Lstd
0,1985,1116,1234,1,9,8,21,12,20,10,...,76.250000,56.700000,58,50,111,68,71.5,54.5,14.519950,6.147267
1,1985,1116,1385,0,9,1,21,12,27,3,...,76.888889,69.333333,47,59,97,80,77.0,69.0,12.175132,8.877473
2,1985,1207,1385,1,1,1,25,2,27,3,...,76.888889,69.333333,47,59,97,80,77.0,69.0,12.175132,8.877473
3,1985,1246,1385,0,12,1,16,12,27,3,...,76.888889,69.333333,47,59,97,80,77.0,69.0,12.175132,8.877473
4,1985,1380,1385,0,16,1,18,10,27,3,...,76.888889,69.333333,47,59,97,80,77.0,69.0,12.175132,8.877473
5,1985,1301,1385,0,3,1,20,9,27,3,...,76.888889,69.333333,47,59,97,80,77.0,69.0,12.175132,8.877473
6,1985,1120,1345,1,11,6,18,11,17,8,...,70.058824,67.125000,50,43,85,84,72.0,66.5,9.555565,12.368595
7,1985,1120,1242,1,11,3,18,11,23,7,...,78.652174,67.428571,58,46,91,89,78.0,70.0,8.637175,14.842025
8,1985,1120,1314,0,11,2,18,11,23,8,...,77.304348,67.375000,57,50,89,82,78.0,69.0,8.248554,11.511588
9,1985,1292,1314,0,15,2,13,13,23,8,...,77.304348,67.375000,57,50,89,82,78.0,69.0,8.248554,11.511588

In [864]:
test.head(10)

,Id,Pred,year,team1,team2,team1Seed,team2Seed,team1wins,team1losses,team2wins,...,team2WAverage,team2LAverage,team2Wmin,team2Lmin,team2Wmax,team2Lmax,team2Wmedian,team2Lmedian,team2Wstd,team2Lstd
0,2016_1112_1114,0.5,2016,1112,1114,6,12,25,8,27,...,70.333333,67.750000,49,53,89,82,72.0,68.0,9.261168,12.526638
1,2016_1112_1122,0.5,2016,1112,1122,6,16,25,8,16,...,83.375000,66.588235,73,41,97,86,83.0,68.0,7.290073,11.964892
2,2016_1112_1124,0.5,2016,1112,1124,6,5,25,8,21,...,81.857143,65.727273,63,58,100,74,80.0,66.0,10.191485,5.375132
3,2016_1112_1138,0.5,2016,1112,1138,6,14,25,8,19,...,82.842105,68.142857,64,58,99,96,80.0,69.0,8.886023,9.518267
4,2016_1112_1139,0.5,2016,1112,1139,6,9,25,8,21,...,87.666667,65.700000,67,55,144,75,88.0,67.5,14.729397,6.341473
5,2016_1112_1143,0.5,2016,1112,1143,6,4,25,8,23,...,78.130435,68.200000,63,58,97,90,78.0,64.5,7.848777,9.284213
6,2016_1112_1151,0.5,2016,1112,1151,6,12,25,8,27,...,77.629630,59.400000,59,54,125,64,77.0,61.0,13.217911,4.188219
7,2016_1112_1153,0.5,2016,1112,1153,6,9,25,8,22,...,75.454545,68.200000,54,55,106,97,72.5,66.5,14.373713,12.542989
8,2016_1112_1160,0.5,2016,1112,1160,6,8,25,8,21,...,81.619048,63.636364,56,53,95,83,82.0,62.0,9.280089,9.859683
9,2016_1112_1163,0.5,2016,1112,1163,6,9,25,8,24,...,78.458333,61.300000,60,51,104,76,76.0,59.0,10.881558,7.901541

In [865]:
##Saving results in an array trainlabels
trainlabels = train.result.values
train.drop('result', inplace=True, axis=1)
train.fillna(-1, inplace=True)
testids = test.Id.values
test.drop(['Id', 'Pred'], inplace=True, axis=1)
test.fillna(1, inplace=True)

Standardize features by removing the mean and scaling to unit variance

In [866]:
ss = StandardScaler()

In [867]:
ss

StandardScaler(copy=True, with_mean=True, with_std=True)

In [868]:
train[train.columns] = np.round(ss.fit_transform(train), 5)
test[test.columns] = np.round(ss.transform(test), 5)

In [869]:
train.head(10)

,year,team1,team2,team1Seed,team2Seed,team1wins,team1losses,team2wins,team2losses,team1WAverage,...,team2WAverage,team2LAverage,team2Wmin,team2Lmin,team2Wmax,team2Lmax,team2Wmedian,team2Lmedian,team2Wstd,team2Lstd
0,-1.68762,-1.37788,-1.38232,0.47346,0.26296,-0.49979,1.43811,-0.77880,0.81324,-1.55780,...,-0.37470,-1.25514,-0.10116,-0.50149,0.73048,-1.13743,-0.99261,-1.42399,1.54848,-0.81849
1,-1.68762,-1.37788,0.43918,0.47346,-1.28241,-0.49979,1.43811,1.14137,-1.53220,-1.55780,...,-0.28005,0.26580,-1.72603,0.47559,-0.40940,-0.06059,-0.18486,0.26021,0.52973,0.01802
2,-1.68762,-0.25351,0.43918,-1.23435,-1.28241,0.53690,-1.75215,1.14137,-1.53220,-0.41761,...,-0.28005,0.26580,-1.72603,0.47559,-0.40940,-0.06059,-0.18486,0.26021,0.52973,0.01802
3,-1.68762,0.22836,0.43918,1.11388,-1.28241,-1.79565,1.43811,1.14137,-1.53220,-1.75365,...,-0.28005,0.26580,-1.72603,0.47559,-0.40940,-0.06059,-0.18486,0.26021,0.52973,0.01802
4,-1.68762,1.88401,0.43918,1.96778,-1.28241,-1.27731,0.80006,1.14137,-1.53220,1.71166,...,-0.28005,0.26580,-1.72603,0.47559,-0.40940,-0.06059,-0.18486,0.26021,0.52973,0.01802
5,-1.68762,0.90792,0.43918,-0.80739,-1.28241,-0.75896,0.48103,1.14137,-1.53220,-0.15645,...,-0.28005,0.26580,-1.72603,0.47559,-0.40940,-0.06059,-0.18486,0.26021,0.52973,0.01802
6,-1.68762,-1.32845,-0.04334,0.90041,-0.17857,-1.27731,1.11909,-1.60173,0.14312,-1.00977,...,-1.29197,-0.00007,-1.28289,-1.26144,-1.38644,0.29835,-0.91918,-0.03017,-0.60839,1.08765
7,-1.68762,-1.32845,-1.28582,0.90041,-0.84088,-1.27731,1.11909,0.04413,-0.19195,-1.00977,...,-0.01880,0.03648,-0.10116,-0.93574,-0.89792,0.74703,-0.03799,0.37637,-1.00741,1.84548
8,-1.68762,-1.32845,-0.41729,0.90041,-1.06165,-1.27731,1.11909,0.04413,0.14312,-1.00977,...,-0.21849,0.03003,-0.24887,-0.50149,-1.06076,0.11888,-0.03799,0.26021,-1.17625,0.82508
9,-1.68762,0.79672,-0.41729,1.75431,-1.06165,-2.57317,1.75714,0.04413,0.14312,-1.77777,...,-0.21849,0.03003,-0.24887,-0.50149,-1.06076,0.11888,-0.03799,0.26021,-1.17625,0.82508

In [870]:
X_train = train
X_test = test
target = trainlabels

In [871]:
target

array([1, 0, 1, ..., 1, 0, 1])

##Training Model##

In [872]:
print('Training...')
rfc = RandomForestClassifier(n_estimators=500, max_features= 22, criterion= 'entropy', min_samples_split=1, max_depth= 50, min_samples_leaf=148, n_jobs = -1)

Training...

In [873]:
#X_test.drop('team2Lstd',inplace=True, axis=1)
X_test.head(10)

,year,team1,team2,team1Seed,team2Seed,team1wins,team1losses,team2wins,team2losses,team1WAverage,...,team2WAverage,team2LAverage,team2Wmin,team2Lmin,team2Wmax,team2Lmax,team2Wmedian,team2Lmedian,team2Wstd,team2Lstd
0,1.76358,-1.4273,-2.82988,-0.16697,1.14603,0.5369,0.16201,1.14137,-1.19714,0.40865,...,-1.25130,0.07518,-1.43060,-0.17579,-1.06076,0.11888,-0.91918,0.14406,-0.73630,1.13607
1,1.76358,-1.4273,-2.73337,-0.16697,2.02910,0.5369,0.16201,-1.87604,3.15868,0.40865,...,0.68091,-0.06469,2.11458,-1.47857,-0.40940,0.47782,0.69633,0.14406,-1.59268,0.96396
2,1.76358,-1.4273,-2.70925,-0.16697,-0.39934,0.5369,0.16201,-0.50449,1.14830,0.40865,...,0.45603,-0.16834,0.63742,0.36703,-0.16514,-0.59901,0.25573,-0.08824,-0.33211,-1.05506
3,1.76358,-1.4273,-2.54037,-0.16697,1.58757,0.5369,0.16201,-1.05311,2.15349,0.40865,...,0.60196,0.12247,0.78514,0.36703,-0.24656,1.37518,0.25573,0.26021,-0.89929,0.21435
4,1.76358,-1.4273,-2.52830,-0.16697,0.48373,0.5369,0.16201,-0.50449,0.81324,0.40865,...,1.31675,-0.17162,1.22828,0.04133,3.41735,-0.50927,1.43065,0.08599,1.63948,-0.75898
5,1.76358,-1.4273,-2.48005,-0.16697,-0.62011,0.5369,0.16201,0.04413,0.81324,0.40865,...,-0.09610,0.12935,0.63742,0.36703,-0.40940,0.83677,-0.03799,-0.26247,-1.34994,0.14264
6,1.76358,-1.4273,-2.38355,-0.16697,1.14603,0.5369,0.16201,1.14137,-0.86207,0.40865,...,-0.17030,-0.93008,0.04656,-0.06723,1.87037,-1.49637,-0.18486,-0.66900,0.98278,-1.41871
7,1.76358,-1.4273,-2.35942,-0.16697,0.48373,0.5369,0.16201,-0.23018,0.81324,0.40865,...,-0.49255,0.12935,-0.69202,0.04133,0.32338,1.46492,-0.84575,-0.03017,1.48494,1.14108
8,1.76358,-1.4273,-2.27498,-0.16697,0.26296,0.5369,0.16201,-0.50449,1.14830,0.40865,...,0.42076,-0.42007,-0.39659,-0.17579,-0.57224,0.20861,0.54946,-0.55285,-0.72808,0.31895
9,1.76358,-1.4273,-2.23879,-0.16697,0.48373,0.5369,0.16201,0.31844,0.81324,0.40865,...,-0.04752,-0.70134,0.19427,-0.39292,0.16054,-0.41954,-0.33172,-0.90131,-0.03229,-0.28100

In [874]:
# Fitting 
rfc.fit(X_train,target) 
x_pred = rfc.predict_proba(X_train)

In [875]:

y_pred = rfc.predict_proba(X_test)

In [876]:
#testids

In [877]:

# Making submission
submission = pd.DataFrame({'Id': testids,
                           'Pred': np.clip(y_pred[:,1], 1e-6, 1-1e-6)})
submission.to_csv('MLsubmission.csv', index=False)
print('Finished')

Finished